server:
  port: 8089

spring:
  application:
    name: gateway

  sleuth:
    sampler:
      probability: 1.0 # 기본값 0.1  샘플링 정의 0~1(100%)
  zipkin:
    base-url: http://127.0.0.1:9411/

  config:
    import:
      - "optional:configserver:http://localhost:8091"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      httpclient:
        connect-timeout: 10000
        response-timeout: 10s

#       default-filters:
#           -   name: GlobalFilter
#               args:
#                   preLogger: true
#                   postLogger: true

      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*),/$\{path}
        #                        - CustomFilter

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**
          filters:
            - RewritePath=/cart-service/(?<path>.*),/$\{path}
        #                        - CustomFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*),/$\{path}
        #                        - CustomFilter

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/**
          filters:
            - RewritePath=/catalog-service/(?<path>.*),/$\{path}


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

logging:
  level:
    root: info
    reactor.netty.http.server.AccessLog: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - "info"
          - "env"
          - "refresh"
          - "bus-refresh"
          - "bus-env"
          - "health"
          - "trace"
          - "prometheus"
          - "metrics"
  endpoint:
    gateway:
      enabled: true
