server:
  port: 8901

spring:
  application:
    name: auth-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: create-drop
    showSql: true

    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

security:
  oauth2:
#    jwt:
#      signkey: 123@#$
    authorization:
      check-token-access: isAuthenticated()
#    client:
#      client-id: clientId
#      client-secret: clientSecret
#
#    resource.jwt.key-value: jwt_secret_key
#
