server:
  port: 8901

spring:
  application:
    name: auth-service

  h2.console:
    enabled: true
    path: /h2-console

security.oauth2:
  client:
    client-id: auth_id
    client-secret: auth_secret

  resource.jwt.key-value: jwt_secret_key

